-- Liquibase formatted SQL
-- changeset belpost:001-create-tables

CREATE TABLE categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id    BIGINT,
    name         VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE publications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(2000),
    image_url    VARCHAR(255),
    period       VARCHAR(255) NOT NULL,
    price        DOUBLE PRECISION NOT NULL,
    type         VARCHAR(50) NOT NULL
);

CREATE TABLE subscriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id  BIGINT NOT NULL,
    customer_name   VARCHAR(255) NOT NULL,
    customer_email  VARCHAR(255) NOT NULL,
    customer_phone  VARCHAR(255) NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    period          VARCHAR(255) NOT NULL,
    total_price     DOUBLE PRECISION NOT NULL,
    status          VARCHAR(50) NOT NULL
);

CREATE TABLE publication_category (
    category_id     BIGINT NOT NULL,
    publication_id  BIGINT NOT NULL,
    PRIMARY KEY (category_id, publication_id)
);

ALTER TABLE categories
    ADD CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id) REFERENCES categories (id);

ALTER TABLE publication_category
    ADD CONSTRAINT fk_pub_cat_category
        FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE publication_category
    ADD CONSTRAINT fk_pub_cat_publication
        FOREIGN KEY (publication_id) REFERENCES publications (id);

ALTER TABLE subscriptions
    ADD CONSTRAINT fk_subscriptions_publication
        FOREIGN KEY (publication_id) REFERENCES publications (id);

