-- Liquibase formatted SQL
-- changeset belpost:002-create-cart-tables

CREATE TABLE carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    cart_token VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE cart_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id        BIGINT NOT NULL,
    publication_id BIGINT NOT NULL,
    period         VARCHAR(255) NOT NULL,
    quantity       INT NOT NULL
);

ALTER TABLE cart_items
    ADD CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE cart_items
    ADD CONSTRAINT fk_cart_items_publication
        FOREIGN KEY (publication_id) REFERENCES publications (id);

