-- Liquibase formatted SQL
-- changeset belpost:003-create-users-and-relations

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    phone         VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL
);

ALTER TABLE carts
    ADD CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE subscriptions
    ADD COLUMN user_id BIGINT;

ALTER TABLE subscriptions
    ADD CONSTRAINT fk_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES users (id);

